### ISSUE TITLE
Trouble with MoveTank.on

### ISSUE THREAD

**Issue by stephan-ack** [QuirkyCort/ev3dev-lang-python-fast#6] opened 2020-09-16 16:23 UTC
I am trying to implement some manual turning based on an gyro measurement.
My class calls MoveTank.on with the parameters 10 and -10, but i get following error:

  File "/home/robot/FunctionBased_doNotUsed/main.py", line 151, in turn
    self.drive_manual.on(SpeedPercent(left_speed), SpeedPercent(right_speed))
  File "/home/robot/FunctionBased_doNotUsed/ev3fast.py", line 1452, in on
    self.right_motor.speed_sp = right_speed_var
  File "/home/robot/FunctionBased_doNotUsed/ev3fast.py", line 834, in speed_sp
    os.write(self._fd['speed_sp'], self.speed_sp_table[value])
OSError: [Errno 22] Invalid argument

Any help here?

(Oh and btw, have not had a chance to test micropython today, will try and see if i can find time tomorrow)

**Comment by QuirkyCort** [comment] 2020-09-17 02:05
Didn't have a chance to test it out, but I think that a table-lookup that was added a long time back to optimize performance is the cause of the problem. It should be fixed now (...don't have an EV3 with me to test). Let me know if things are still not working right.

**Comment by stephan-ack** [comment] 2020-09-17 07:54
Hello, thanks for the quick response! 👍 
Your fix works, great job.

**Closed as completed** 2020-09-27 15:37 UTC
